image: ruby:2.1
  
stages:
  - build
  - test

composer:
  stage: build
  script:
    - docker run composer/composer -d Game install

phpunit:
  stage: test
  script:
    - docker run phpunit/phpunit --colors --verbose --configuration Game/phpunit.xml --testsuite unit --coverage-html Game/test-results/unit
